### ISSUE TITLE
Why GPL 3.0?

### ISSUE THREAD

**Issue by busterb** [Arvanaghi/CheckPlease#2]
If this library is for integrating within other projects, this doesn't seem like a great license to use.

**Comment by ChrisTruncer** [comment]
There really isn't much to say here. This isn't what github issues are used for. We chose this because it clearly can be shared and used by others.

**Comment by ChrisTruncer** [comment]
We definitely welcome the use with any other tool, and are happy to share it

**Comment by ChrisTruncer** [comment]
Sorry for multiple responses, on a plane and trying to type on my phone. We used GPLv3 because we do want it to be used by anyone who wants it. The only stipulation is if any of the code is modified, that the modification needs to be released. We chose this because if the code can be optimized, or made better some how, we'd like to learn how to do that too. That's the main reason for GPLv3.

Hope that helps, sorry for multiple responses and deletions of previous comments.
